CREATE DATABASE IF NOT EXISTS STUDENT_DB;

USE STUDENT_DB;

--Careful with this in production
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE IF NOT EXISTS STUDENT
(SSN STRING, FIRST_NAME STRING, LAST_NAME STRING, RACE STRING, AGE INT, STATE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';
